version: '3.9'

services:
  credit-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nttfinal-credit-service
    ports:
      - "7004:7004"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: optional:configserver:http://host.docker.internal:8888/
      EUREKA_DEFAULT_ZONE: http://host.docker.internal:8761/eureka
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/credit_db
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      CREDIT_CUSTOMER_SERVICE_BASE_URL: http://host.docker.internal:7002
      JWT_SECRET: change_this_secret_in_real_env_min_32_chars
    depends_on:
      - mongodb
      - redis
      - zookeeper
      - kafka

  mongodb:
    image: mongo:7.0
    container_name: nttfinal-credit-mongodb
    ports:
      - "27019:27017"
    volumes:
      - credit_mongo_data:/data/db

  redis:
    image: redis:7
    container_name: nttfinal-credit-redis
    ports:
      - "6381:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: nttfinal-credit-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: nttfinal-credit-kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  credit_mongo_data:
